#!/usr/bin/env php
<?php

session_start();
ini_set('display_errors',1);
date_default_timezone_set("America/Chicago");
define('ROOT_DIR', dirname(__FILE__));
define('APP_DIR', dirname(__FILE__)."/app");
define('LIB_DIR', dirname(__FILE__)."/lib");
define('PUBLIC_DIR', dirname(__FILE__)."/public");
require_once(ROOT_DIR.'/lib/GitFloat/Config.php');

// Get the composer json
$contents = file_get_contents('composer.json');

// Turn it to php
$parsed = json_decode($contents);

// Get our widgets
$pages = \GitFloat\Config::get('widgets');


// Add each widgets class location to the autoloader
foreach($pages as $page) {
	foreach($page as $widget) {
		$parts = explode("/", $widget);
		$author = $parts[0];
		$branch = explode("_", $parts[1]);
		$auth = array_shift($branch);
		$name = implode("_", $branch);
		$namespace = str_replace("/", "\\", ucwords($author."/".$auth."/".$name, '/_-'))."\\";
		$parsed->autoload->{'psr-4'}->$namespace = "app/import/$author/$auth/$name/classes/";
		if($author != "Custom") {
			shell_exec("git clone -b ".$auth."_".$name." https://github.com/$author/GitFloat-Widgets ./app/import/$author/$auth/$name");
		}
	}
}
// Save the json
file_put_contents('composer.json', json_encode($parsed, JSON_PRETTY_PRINT));

// Redo composer
shell_exec('./composer.phar update');